services:
  app:
    build:
      dockerfile: ./.docker/Dockerfile
    environment:
      APP_ENV: 'dev'
      DATABASE_URL: 'mysql://root:mysql@mysql/rh_bundle%kernel.environment%?charset=utf8mb4'
    working_dir: /app/tests/Application
    volumes:
      - ./:/app:delegated
      - ./.docker/apache/default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${APP_PORT:-80}:80
    depends_on:
      - mysql
    networks:
      - campings_rh

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      - campings_rh

networks:
  campings_rh:
    driver: bridge
